### PR TITLE
Add support for config.json

### PR DESCRIPTION
**Pull request by cdeletre**
This PR adds the support of a configuration file.

### Config file
-----
`config.json` can be used to configure some parameters. Here is an exemple:

```json
{
    "save_dir" : "gamedata",
    "apk_path" : "my_game.apk",
    "show_cursor": false
}
```

### CODE REVIEW

**Comment by JeodC** [comment]
Does this `config.json` live next to the gmloadernext binary? Some games use their own `config.json` file, which would be in `gamedata`. Should the json we use for gmloader be renamed to differentiate better?

**Comment by cdeletre** [comment]
> Does this `config.json` live next to the gmloadernext binary? Some games use their own `config.json` file, which would be in `gamedata`. Should the json we use for gmloader be renamed to differentiate better?

You are right. how about `gmloader.conf` ? I can also add the support for `-c whatever.conf` as an optional command line argument.

**Comment by JeodC** [comment]
> > Does this `config.json` live next to the gmloadernext binary? Some games use their own `config.json` file, which would be in `gamedata`. Should the json we use for gmloader be renamed to differentiate better?
> 
> You are right. how about `gmloader.conf` ? I can also add the support for `-c whatever.conf` as an optional command line argument.
> 
> (and yes config.json lives next to gmloadernext binary)

The argument might work well, I suggest going with that. I believe we already use a standard {gamename}.gptk file, so we can just keep to that standard for gmloader config files.

**Comment by cdeletre** [comment]
```
./build/aarch64-linux-gnu/gmloader/gmloader -c configuration.gmld
Loading config file (/devel/gmloader-next/configuration.gmld)
	save_dir = gamedata
	apk_path = my_game.apk
	show_cursor = 1
```

Update done

**Review by JeodC — APPROVED** [review]

**Pull request merged**
